-- ============================================================
-- M1 fix: add WITH CHECK to UPDATE policies
-- ============================================================
-- quotations / deals / samples / reminders and the *_items tables had
-- UPDATE RLS policies with a USING clause but no WITH CHECK. USING only
-- vets the OLD row, so a member could UPDATE a row they own and set its
-- customer_id (or a reminder's assigned_to) to a value they do NOT own
-- — silently moving the row out of their scope. customers_update was
-- given a WITH CHECK in an earlier migration; these siblings were not.
--
-- Fix: set each UPDATE policy's WITH CHECK equal to its USING clause, so
-- the post-update row must satisfy the same ownership test.
-- ============================================================

-- ----------------------------------------------------------
-- Phase 3a Neon port: Supabase-specific SQL stripped above
-- (RLS policies / grants / storage / pg_cron). See top of
-- 20260514091040_initial_schema.sql for the auth.uid() stub.
-- ----------------------------------------------------------
